### ISSUE TITLE
Desired schema

### ISSUE THREAD

**Issue by mheiber** [vdavez/dc-contracts#12]
It would be good if scrapers for these sites could output csv files that all fit the same schema. I don't know much about procurement. Could you specify column names and descriptions?

**Comment by vdavez** [comment]
Been thinking about this issue for a bit and am cc'ing @konklone. Would it be feasible to run the json file automatically through http://konklone.io/json?

**Comment by mheiber** [comment]
The online converter looks cool.
I just meant that the tables on the different pages you link to all have different column headers:

<table>
<tr>
<td>Notice Date</td>    <td>Response Due Date   </td><td>Caption and Description</td><td>   Vendor Name</td>    <td>Agency</td> <td>Point of Contact</td></tr></table>

vs.

<table><tr>
<td>"Solicitation Number</td><td>   Caption</td><td>    Closing Date</td><td>   Closing Time</td>   <td>Issuance Date</td><td>  Agency</td><td> Market Type</td><td>    Status</td>
</tr></table>

In order to mash the data together in meaningful ways, the tables would need to have a more consistent schema.
I'm sure it's OK to just grab the tables and worry about this later, though.

**Comment by vdavez** [comment]
Yeah. Good points. I'll work on standardizing the schema.
