### ISSUE TITLE
DCPL Contract Awards Scraper

### ISSUE THREAD

**Issue by mheiber** [vdavez/dc-contracts#13]
I made a scraper for DCPS Contract Awards:
http://dcps.dc.gov/DCPS/About+DCPS/Doing+Business+with+DCPS/Procurement/Awarded+Contracts

Should I pull request? What folder should I put it in?
JSON or CSV?

Thanks

**Comment by vdavez** [comment]
Sweet! Create a new file and do a pull request. I'll refactor this weekend.

**Comment by vdavez** [comment]
Realize that was ambiguous... Create new files in `/scrapers/`

**Comment by mheiber** [comment]
Cool. And is JSON or CSV better?

**Comment by vdavez** [comment]
Totally agnostic. It might actually make sense to have it in CSV, so I can convert to JSON for the website but also to take advantage of the github rendering...
